version = 0.1

[default.deploy.parameters]
stack_name = "BenchmarkAccuracyETLStack"
resolve_s3 = true
s3_prefix = "BenchmarkAccuracyETLStack"
profile = "wellflat"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BucketName=\"test-elements-benchmark-artifacts\" TableName=\"test-benchmark-result\""
image_repositories = []

[default.global.parameters]
region = "ap-northeast-1"
